name: SQL Autograding

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  grade:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install mysql-client -y

      - name: Wait for MySQL
        run: |
          until mysql -h127.0.0.1 -uroot -proot -e "SELECT 1";
          do
            sleep 3
          done

      - name: Execute Student SQL
        run: |
          mysql -h127.0.0.1 -uroot -proot < starter.sql

      - name: Test Database Exists
        run: |
          mysql -h127.0.0.1 -uroot -proot -e "SHOW DATABASES LIKE 'CollegeDB';"

      - name: Test Department Table Exists
        run: |
          mysql -h127.0.0.1 -uroot -proot -e "USE CollegeDB; SHOW TABLES LIKE 'Department';"

      - name: Verify Table Structure
        run: |
          mysql -h127.0.0.1 -uroot -proot -e "
          USE CollegeDB;
          DESCRIBE Department;
          "
